name: Assemble Setup

on:
  workflow_call:

jobs:
  assembleDebug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Gradlew Permissions
        run: chmod +x ./gradlew

      - name: Execute Gradlew Command
        run: ./gradlew assembleDebug

